<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <?php echo $this->headScript(); ?>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink(); ?>

    <title>Treinamento Open Labs</title>
	
    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
	 <link href="css/tether.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="css/starter-template.css" rel="stylesheet">
    <link href="css/estilo.css" rel="stylesheet">
    
    <script src="js/jquery.min.js" ></script>
    <script src="js/tether.min.js" ></script>
    <script src="js/bootstrap.min.js" ></script>
    <script src="js/functions.js" ></script>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Open Labs</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <!--<li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>-->
          
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cadastros</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
             <!-- <a class="dropdown-item" href="#">Clientes</a>-->
              <a class="dropdown-item load-page" href="#" data-url="http://treinamento-eduardonalves367336.codeanyapp.com/treinamento/public/terminal/index">Terminais</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">

        
		 
		<div id="carregaAjax">
		  <!-- Global notification handling to use call flashMessenger action helper -->
		    <?php if(isset($this->message)) :?>
		    <div class="notification">
		    <?php echo $this->message ;?>
		    </div>   
				<?php endif;?>
		  <?php echo $this->layout()->content; ?> 
		  <?php echo $this->inlineScript(); ?>
		</div> 
		<div class="modal js-loading-bar">
		 <div class="modal-dialog">
			 <div class="modal-content">
				 <div class="modal-body">
					 <div class="progress progress-popup">
						<div class="progress-bar"></div>
					 </div>
				 </div>
			 </div>
		 </div>
		</div>		
		

    </div><!-- /.container -->


   
  </body>
</html>
