<form action="<?=$this->escape($this->element->getAction());?>" 
			method="<?=$this->escape($this->element->getMethod());?>" 
			name="<?=$this->escape($this->element->getName());?>"
			id="<?=$this->escape($this->element->getName());?>">
    <fieldset>
        <legend>Formulário de Cadastro:</legend>
        <br/>
        <?=$this->element->terminal;?>
        <br/>
        <?=$this->element->data_inicio;?>
        <br/>
         <?=$this->element->data_fim;?>
         <br/>
         <button type="submit">Salvar</button>
    </fieldset>	
 </form>   