<h5>
  Visualização do Terminal
</h5>
<br>
<div class="col-md-3">
  <p>
    Terminal: <?php echo $this->terminal['terminal']; ?>
  </p>
</div>
<div class="col-md-3">
  <p>
    Data Iníco: <?php echo $this->terminal['data_inicio']; ?>
  </p>
</div>
<div class="col-md-3">
  <p>
    Data Fim: <?php echo $this->terminal['data_fim']; ?>
  </p>
</div>
<div class="col-md-3">
  <p>
    UF: <?php echo $this->terminal['uf']; ?>
  </p>
</div>